### ISSUE TITLE
"Not purging inner CDN for null due to missing fastly credentials"

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-purge#105]
**Description**
As of 1.5.14 we're seeing the following error msg in the logs: 
```
Not purging inner CDN for null due to missing fastly credentials
```

Logs: https://helix.coralogix.com/#/query/logs?id=2GMiohKfrn3

Looking at the [code](https://github.com/adobe/helix-purge/blob/main/src/index.js#L98-L108) it seems that at least `host` and `path` are null. 

@trieloff Regression of https://github.com/adobe/helix-purge/pull/103

**Version:**
`helix-purge` `1.5.14`

**Comment by trieloff** [comment]
Maybe some integration test?

**Comment by dominique-pfister** [comment]
This was the purge Google Apps Script running every hour. It used to work with version <= 1.5.13 and now stopped working, which explains why I had to do a manual on `blog.adobe.com` yesterday.

The `purge.gs` script looks like this:
```
const url = 'https://adobeioruntime.net/api/v1/web/helix/helix-services/purge@v2?blocking=true&result=true';
const response = UrlFetchApp.fetch(
  url, {
    method: 'POST',
    muteHttpExceptions: true,
    contentType: 'application/json',
    payload: JSON.stringify({ path: resource, xfh: host }),
  },
);
```
I can see that the `main` function in helix-purge changed as follows in 1.5.14:
```
-async function main({
-  host, xfh = '', path = '', HLX_PAGES_FASTLY_SVC_ID, HLX_PAGES_FASTLY_TOKEN, __ow_logger: log,
-}) {
+async function main(req, context) {
+  const { searchParams } = new URL(req.url);
+  const host = searchParams.get('host');
+  const path = searchParams.get('path') || '';
+  const xfh = searchParams.get('xfh') || '';
```
Somehow, after this change the parameter value for `xfh` has become `null` when invoked as above.

**Comment by trieloff** [comment]
I see what the issue is, but it's only indirectly related to the code change in #103:

- universal runtime expects all functions to be web actions
- @dominique-pfister's script is invoking it like a non-web action
- consequently, the URL params that would be present for a web action are absent
- and the action is not able to do something meaningful

The easiest fix would be to change the script invocation to:

```
POST https://adobeioruntime.net/api/v1/web/helix/helix-services/purge@v2?host=...&path=...
```

**Comment by dominique-pfister** [comment]
Not sure I understand: according to [OpenWhisk web actions](https://github.com/apache/openwhisk/blob/master/docs/webactions.md#web-actions):
> Query and body parameters as input: the action receives query parameters as well as parameters in the request body. The precedence order for merging parameters is: package parameters, binding parameters, action parameters, query parameter, body parameters with each of these overriding any previous values in case of overlap .

What about the way the purge script invokes the action is not "web-action" like?

**Comment by dominique-pfister** [comment]
Don't get me wrong, I have no trouble changing the purge script, I'm just wondering whether that wouldn't break client code in other locations...

**Comment by trieloff** [comment]
The blocking and result parameters are straight from OpenWhisk (non-web) API.

So, adding parameter extraction from the request body in `helix-purge` would be another possible fix.

But as far as I know, the vast majority of invocations come through Fastly without a request body.

**Comment by stefan-guggisberg** [comment]
I agree with @trieloff. I guess it's easiest for now to change the script (and use the latest `helix-purge` version).

**Comment by trieloff** [comment]
I can take a look at adding POST body support next week - we need it to make Helix-publish and helix-logging universal, but the quick and safe fix is to use URL parameters in the script.

**Comment by dominique-pfister** [comment]
Yep, looked easy enough, but no one told me that Google Apps Script has neither URL class nor URLSearchParams 😄 

Fixed, and switched back to `purge@v1`

**Comment by stefan-guggisberg** [comment]
Issue is still there, reopening

https://helix.coralogix.com/#/query/logs?id=2GNJ4GNCO0e

**Comment by dominique-pfister** [comment]
I know that these warnings are ugly, but they don't actually indicate a problem: the purge script just needs to purge URLs on the `X-Forwarded-Host (xfh)`, so it doesn't pass a `host` parameter. The resulting behaviour is intentional: `helix-purge` will skip `purgeInner` with that warning, but still call `purgeOuter` using HTTP method `PURGE` on that host.

You might wonder, why the purge script does not execute HTTP method `PURGE` itself: in Google Apps Script, the component `UrlFetchApp` which handles outgoing HTTP calls, will not accept `PURGE` as HTTP method 🙄

**Comment by trieloff** [comment]
If `host` is unset, we should just `info` – if host is set, but the Fastly credentials aren't there, `warn`

**Comment by tripodsan** [comment]
maybe the problem is in the universal adapter, it might not understand the POST body

**Comment by tripodsan** [comment]
also see: https://helix.coralogix.com/#/query/logs?id=2IJajHsQkMg
